services:
    voltix-front:
       image: igrowker/voltix-front
       restart: unless-stopped
       build:
         context: .
         dockerfile: Dockerfile
       working_dir: /usr/share/nginx/html
       networks:
         - voltix
       ports:
         - "8080:80"
       volumes:
         - ./public:/usr/share/html/public
         - "/etc/timezone:/etc/timezone:ro"
         - "/etc/localtime:/etc/localtime:ro"

networks:
  voltix:
    name: voltix
    external: true